apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: env-cf
                key: DB_HOST
        volumeMounts:
          - mountPath: /mount
            name: config

      volumes:
        - name: config
          configMap:
            name: env-cf
